### ISSUE TITLE
Schedule running it? 

### ISSUE THREAD

**Issue by Eagle1337** [Laim/Snap2HTML#3]
I don't think the original could run via task scheduling, but is there a way for this fork to do it? I want to update the HTMLs automatically on a schedule.

**Comment by Laim** [comment]
I can definitely have a look at it.  Will let you know!

**Comment by Laim** [comment]
I'm going to do some general cleanup of the code as the way that the Command Line is done at the moment is a bit odd (in my opinion, I could be wrong lol).

This is on the to-do list for v3 though, you can keep an eye on progress on the dev branch for progress. :)

**Comment by Laim** [comment]
This will be available by this weekend.  Preview 2 (available under releases) has everything split so you could try it now if you wish, there's just a couple of things that need changed as the information from -h/-help is currently wrong.

**Comment by Laim** [comment]
Hey @Eagle1337 

Version 3 has now been released which will allow you to run the application in a schedule.  The GUI and Command Line have been split out, so to schedule it you'll want to use the CLI.

Assuming you're using Task Scheduler, this is the action I tested with it:

![image](https://github.com/Laim/Snap2HTML-NG/assets/14845036/f4822871-a1ec-44e6-8a6d-327a9004d92f)

**Arguments:** -path:"C:\Users\Laim\Pictures" -output:"C:\Users\Laim\Desktop" -randomize 
**Program/script:** Snap2HTML-NG.CLI.exe
**Start in:** C:\Temp\Snap2HTML-NG\

(see HELP.md or run **Snap2HTML-NG.CLI.exe -h** in CMD for new arguments if you have used them previously as it has changed slightly)

Any issues, let me know.
