### ISSUE TITLE
Question "Fix title being overwritten with snapshot of root"

### ISSUE THREAD

**Issue by RustleThyJimmies** [Laim/Snap2HTML#7]
Hi, I was just wondering if the issue in question: "Fix title being overwritten with snapshot of root" will be released with 3.1, but 3.1 has not been released yet?

To elaborate, I assume this issue refers to the custom title (input: "Page title") displayed at the top of the .html file that is generated, being automatically reverted to the target directory it generated a snapshot of, after "Create Snapshot" is clicked? I am currently having this issue with 3.0.

Thank you for working on this project!

**Comment by RustleThyJimmies** [comment]
Update: Upon closing and re-opening the application the second time, the custom title no longer seems to revert, but now I get a Microsoft .NET Framework error box that says "Object reference not set to an instance of an object." 

Just wanted to let you know. Thanks!

**Comment by Laim** [comment]
Hey,

I actually finished v3.1 like 9 months ago but apparently never released it lol; will push it this weekend.

**Comment by Laim** [comment]
v3.1 released https://github.com/Laim/Snap2HTML-NG/releases/tag/3.1

Let me know if it works for you. :)
